### ISSUE TITLE
Search bar (Story L)

### ISSUE THREAD

**Issue by Davidbergkvist** [IamMille/widgify#16]
As a user
I want to search the web directly from the start page
So I can explore varius thing on the web

**Acceptance criteria**: A quickly accessible search bar on the front webpage.  
**Business rules**: The only option is to search the web with google.
**Story points**: 3

**Comment by Davidbergkvist** [comment]
It says nowhere which search engine that will be used, but after a search you'll be directed to google.com.

**Comment by Davidbergkvist** [comment]
When searching for something that startas with # no results will show on google.com.

1. Enter #beer 
2. See no beer in google. 👎

**Comment by IamMille** [comment]
Fixed by using 'encodeURIComponent' (instead of 'encodeURI') which encodes hashtags (and more). I will push it after the presentation today.
